### ISSUE TITLE
Sub domain of 'app.draggle.io' 

### ISSUE THREAD

**Issue by Logannford** [Logannford/layowt#90]
I think mono-repo with 'app' being at 'app.draggle.io'

## TODO LIST:

- [x] Start migration to mono-repo with 
- [ ] Check tsconfg files per repo
- [x] Get deployments to vercel
- [x] Set up subdomain 
- [x] Sort out envs for both repis
- [x] Sort out tailwind config inside 'packages/tailwind'
- [x] Sort out Favicons
- [x] Remove packages/dependencies that are no longer being used
- [x] Ensure deployment pipelines only run if that repo has had changes?
